### ISSUE TITLE
Create Chrome Extension / Firefox addon

### ISSUE THREAD

**Issue by seisvelas** [Carlosf96/tinderLikesRMBlur#1]
This seems more logical as a browser extension. I'd be glad to do it with you one of these weekends.

**Comment by Carlosf96** [comment]
Thanks @seisvelas we can definitely make it as a browser extension !

**Comment by Carlosf96** [comment]
> This seems more logical as a browser extension. I'd be glad to do it with you one of these weekends.

Thanks @seisvelas we can definitely make it as a browser extension !
